"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BOARD_SPACES = void 0;
exports.BOARD_SPACES = [
    { id: 'go', name: 'GO', type: 'GO' },
    { id: 'mediterranean', name: 'Mediterranean Avenue', type: 'PROPERTY', price: 60, baseRent: 2, colorGroup: 'Brown', housePrice: 50, rentWithHouses: [10, 30, 90, 160, 250] },
    { id: 'chest1', name: 'Community Chest', type: 'CHEST' },
    { id: 'baltic', name: 'Baltic Avenue', type: 'PROPERTY', price: 60, baseRent: 4, colorGroup: 'Brown', housePrice: 50, rentWithHouses: [20, 60, 180, 320, 450] },
    { id: 'tax1', name: 'Income Tax', type: 'TAX' },
    { id: 'reading', name: 'Reading Railroad', type: 'PROPERTY', price: 200, baseRent: 25, colorGroup: 'Railroad' },
    { id: 'oriental', name: 'Oriental Avenue', type: 'PROPERTY', price: 100, baseRent: 6, colorGroup: 'LightBlue', housePrice: 50, rentWithHouses: [30, 90, 270, 400, 550] },
    { id: 'chance1', name: 'Chance', type: 'CHANCE' },
    { id: 'vermont', name: 'Vermont Avenue', type: 'PROPERTY', price: 100, baseRent: 6, colorGroup: 'LightBlue', housePrice: 50, rentWithHouses: [30, 90, 270, 400, 550] },
    { id: 'connecticut', name: 'Connecticut Avenue', type: 'PROPERTY', price: 120, baseRent: 8, colorGroup: 'LightBlue', housePrice: 50, rentWithHouses: [40, 100, 300, 450, 600] },
    { id: 'jail', name: 'Jail', type: 'JAIL' },
    { id: 'st_charles', name: 'St. Charles Place', type: 'PROPERTY', price: 140, baseRent: 10, colorGroup: 'Pink', housePrice: 100, rentWithHouses: [50, 150, 450, 625, 750] },
    { id: 'electric', name: 'Electric Company', type: 'PROPERTY', price: 150, baseRent: 0, colorGroup: 'Utility' },
    { id: 'states', name: 'States Avenue', type: 'PROPERTY', price: 140, baseRent: 10, colorGroup: 'Pink', housePrice: 100, rentWithHouses: [50, 150, 450, 625, 750] },
    { id: 'virginia', name: 'Virginia Avenue', type: 'PROPERTY', price: 160, baseRent: 12, colorGroup: 'Pink', housePrice: 100, rentWithHouses: [60, 180, 500, 700, 900] },
    { id: 'penn_rr', name: 'Pennsylvania Railroad', type: 'PROPERTY', price: 200, baseRent: 25, colorGroup: 'Railroad' },
    { id: 'st_james', name: 'St. James Place', type: 'PROPERTY', price: 180, baseRent: 14, colorGroup: 'Orange', housePrice: 100, rentWithHouses: [70, 200, 550, 750, 950] },
    { id: 'chest2', name: 'Community Chest', type: 'CHEST' },
    { id: 'tennessee', name: 'Tennessee Avenue', type: 'PROPERTY', price: 180, baseRent: 14, colorGroup: 'Orange', housePrice: 100, rentWithHouses: [70, 200, 550, 750, 950] },
    { id: 'new_york', name: 'New York Avenue', type: 'PROPERTY', price: 200, baseRent: 16, colorGroup: 'Orange', housePrice: 100, rentWithHouses: [80, 220, 600, 800, 1000] },
    { id: 'free_parking', name: 'Free Parking', type: 'FREE_PARKING' },
    { id: 'kentucky', name: 'Kentucky Avenue', type: 'PROPERTY', price: 220, baseRent: 18, colorGroup: 'Red', housePrice: 150, rentWithHouses: [90, 250, 700, 875, 1050] },
    { id: 'chance2', name: 'Chance', type: 'CHANCE' },
    { id: 'indiana', name: 'Indiana Avenue', type: 'PROPERTY', price: 220, baseRent: 18, colorGroup: 'Red', housePrice: 150, rentWithHouses: [90, 250, 700, 875, 1050] },
    { id: 'illinois', name: 'Illinois Avenue', type: 'PROPERTY', price: 240, baseRent: 20, colorGroup: 'Red', housePrice: 150, rentWithHouses: [100, 300, 750, 925, 1100] },
    { id: 'bo_rr', name: 'B. & O. Railroad', type: 'PROPERTY', price: 200, baseRent: 25, colorGroup: 'Railroad' },
    { id: 'atlantic', name: 'Atlantic Avenue', type: 'PROPERTY', price: 260, baseRent: 22, colorGroup: 'Yellow', housePrice: 150, rentWithHouses: [110, 330, 800, 975, 1150] },
    { id: 'ventnor', name: 'Ventnor Avenue', type: 'PROPERTY', price: 260, baseRent: 22, colorGroup: 'Yellow', housePrice: 150, rentWithHouses: [110, 330, 800, 975, 1150] },
    { id: 'water', name: 'Water Works', type: 'PROPERTY', price: 150, baseRent: 0, colorGroup: 'Utility' },
    { id: 'marvin', name: 'Marvin Gardens', type: 'PROPERTY', price: 280, baseRent: 24, colorGroup: 'Yellow', housePrice: 150, rentWithHouses: [120, 360, 850, 1025, 1200] },
    { id: 'go_to_jail', name: 'Go To Jail', type: 'GO_TO_JAIL' },
    { id: 'pacific', name: 'Pacific Avenue', type: 'PROPERTY', price: 300, baseRent: 26, colorGroup: 'Green', housePrice: 200, rentWithHouses: [130, 390, 900, 1100, 1275] },
    { id: 'north_carolina', name: 'North Carolina Avenue', type: 'PROPERTY', price: 300, baseRent: 26, colorGroup: 'Green', housePrice: 200, rentWithHouses: [130, 390, 900, 1100, 1275] },
    { id: 'chest3', name: 'Community Chest', type: 'CHEST' },
    { id: 'pennsylvania', name: 'Pennsylvania Avenue', type: 'PROPERTY', price: 320, baseRent: 28, colorGroup: 'Green', housePrice: 200, rentWithHouses: [150, 450, 1000, 1200, 1400] },
    { id: 'short_line', name: 'Short Line', type: 'PROPERTY', price: 200, baseRent: 25, colorGroup: 'Railroad' },
    { id: 'chance3', name: 'Chance', type: 'CHANCE' },
    { id: 'park_place', name: 'Park Place', type: 'PROPERTY', price: 350, baseRent: 35, colorGroup: 'DarkBlue', housePrice: 200, rentWithHouses: [175, 500, 1100, 1300, 1500] },
    { id: 'tax2', name: 'Luxury Tax', type: 'TAX' },
    { id: 'boardwalk', name: 'Boardwalk', type: 'PROPERTY', price: 400, baseRent: 50, colorGroup: 'DarkBlue', housePrice: 200, rentWithHouses: [200, 600, 1400, 1700, 2000] },
];
